Repository sonata-project/twig-extensions, pull requests merged in 2020-03, with the labels that each got.

#71 Fix PHPStan
  .github/workflows/qa.yml
Labels: pedantic

#70 Allow Twig 3
  composer.json
  tests/TokenParser/DeprecatedTemplateTokenParserTest.php
  tests/TokenParser/TemplateBoxTokenParserTest.php
Labels: minor, vendor

#72 Use `Node::getNode()` with "0" as string instead of `\Iterator::offsetGet(0)`
  tests/TokenParser/DeprecatedTemplateTokenParserTest.php
  tests/TokenParser/TemplateBoxTokenParserTest.php
Labels: pedantic

#57 Import flashmessage.css from CoreBundle
  src/Bridge/Symfony/Resources/public/css/flashmessage.css
Labels: minor
