Repository sonata-project/twig-extensions, pull requests merged in 2021-07, with the labels that each got.

#222 Allow customizing flashbag groups
  src/Bridge/Symfony/Resources/views/FlashMessage/render.html.twig
Labels: feature, minor

#225 Deprecate sonata_urlsafeid in favor of SonataAdminBundle
  src/Extension/TemplateExtension.php
  tests/Extension/TemplateExtensionTest.php
Labels: minor

#227 Fix security issue
  composer.json
Labels: pedantic
